name: Build and Publish TypeDoc

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # 1. 检出主仓库代码
    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        repository: TRSSo/Philia
        ref: lib

    # 2. 检出代码
    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        path: plugin/example
        fetch-depth: 0  # 获取所有历史记录（用于分支操作）

    # 3. 安装 pnpm
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: latest
        run_install: true

    # 4. 生成文档
    - name: Build project
      run: |
        cd plugin/example
        pnpx typedoc --entryPointStrategy Expand --skipErrorChecking src --out temp

    # 5. 推送到 docs 分支
    - name: Push to docs branch
      run: |
        cd plugin/example
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@users.noreply.github.com"
        git checkout docs || git checkout --orphan docs
        cd temp
        mv ../.git .
        git add .
        if git commit -m "$(git log -1 --pretty=%B main)"; then
          git push origin docs -f
        fi
